// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/authorization_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/authorization_repository.go -destination=tests/mocks/authorization_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthCodeRepository is a mock of AuthCodeRepository interface.
type MockAuthCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthCodeRepositoryMockRecorder is the mock recorder for MockAuthCodeRepository.
type MockAuthCodeRepositoryMockRecorder struct {
	mock *MockAuthCodeRepository
}

// NewMockAuthCodeRepository creates a new mock instance.
func NewMockAuthCodeRepository(ctrl *gomock.Controller) *MockAuthCodeRepository {
	mock := &MockAuthCodeRepository{ctrl: ctrl}
	mock.recorder = &MockAuthCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCodeRepository) EXPECT() *MockAuthCodeRepositoryMockRecorder {
	return m.recorder
}

// ExchangeCode mocks base method.
func (m *MockAuthCodeRepository) ExchangeCode(ctx context.Context, code string) (*models.AuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(*models.AuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockAuthCodeRepositoryMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockAuthCodeRepository)(nil).ExchangeCode), ctx, code)
}

// GetClaimsByID mocks base method.
func (m *MockAuthCodeRepository) GetClaimsByID(ctx context.Context, userId []byte) (*models.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClaimsByID", ctx, userId)
	ret0, _ := ret[0].(*models.UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClaimsByID indicates an expected call of GetClaimsByID.
func (mr *MockAuthCodeRepositoryMockRecorder) GetClaimsByID(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClaimsByID", reflect.TypeOf((*MockAuthCodeRepository)(nil).GetClaimsByID), ctx, userId)
}

// GetClientRedirectURI mocks base method.
func (m *MockAuthCodeRepository) GetClientRedirectURI(ctx context.Context, clientID []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientRedirectURI", ctx, clientID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientRedirectURI indicates an expected call of GetClientRedirectURI.
func (mr *MockAuthCodeRepositoryMockRecorder) GetClientRedirectURI(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientRedirectURI", reflect.TypeOf((*MockAuthCodeRepository)(nil).GetClientRedirectURI), ctx, clientID)
}

// GetIDsFromToken mocks base method.
func (m *MockAuthCodeRepository) GetIDsFromToken(ctx context.Context, token string) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDsFromToken", ctx, token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIDsFromToken indicates an expected call of GetIDsFromToken.
func (mr *MockAuthCodeRepositoryMockRecorder) GetIDsFromToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDsFromToken", reflect.TypeOf((*MockAuthCodeRepository)(nil).GetIDsFromToken), ctx, token)
}

// GetUserForAuth mocks base method.
func (m *MockAuthCodeRepository) GetUserForAuth(ctx context.Context, email string) (*models.UserClaims, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForAuth", ctx, email)
	ret0, _ := ret[0].(*models.UserClaims)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserForAuth indicates an expected call of GetUserForAuth.
func (mr *MockAuthCodeRepositoryMockRecorder) GetUserForAuth(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForAuth", reflect.TypeOf((*MockAuthCodeRepository)(nil).GetUserForAuth), ctx, email)
}

// RevokeTokens mocks base method.
func (m *MockAuthCodeRepository) RevokeTokens(ctx context.Context, userID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeTokens indicates an expected call of RevokeTokens.
func (mr *MockAuthCodeRepositoryMockRecorder) RevokeTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeTokens", reflect.TypeOf((*MockAuthCodeRepository)(nil).RevokeTokens), ctx, userID)
}

// RotateRefreshToken mocks base method.
func (m *MockAuthCodeRepository) RotateRefreshToken(ctx context.Context, oldToken, newToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, oldToken, newToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockAuthCodeRepositoryMockRecorder) RotateRefreshToken(ctx, oldToken, newToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockAuthCodeRepository)(nil).RotateRefreshToken), ctx, oldToken, newToken)
}

// StoreCode mocks base method.
func (m *MockAuthCodeRepository) StoreCode(ctx context.Context, code string, userID, clientID []byte, redirectURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreCode", ctx, code, userID, clientID, redirectURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreCode indicates an expected call of StoreCode.
func (mr *MockAuthCodeRepositoryMockRecorder) StoreCode(ctx, code, userID, clientID, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreCode", reflect.TypeOf((*MockAuthCodeRepository)(nil).StoreCode), ctx, code, userID, clientID, redirectURI)
}

// StoreRefreshToken mocks base method.
func (m *MockAuthCodeRepository) StoreRefreshToken(ctx context.Context, token string, userID, clientID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshToken", ctx, token, userID, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshToken indicates an expected call of StoreRefreshToken.
func (mr *MockAuthCodeRepositoryMockRecorder) StoreRefreshToken(ctx, token, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshToken", reflect.TypeOf((*MockAuthCodeRepository)(nil).StoreRefreshToken), ctx, token, userID, clientID)
}

// VerifyClient mocks base method.
func (m *MockAuthCodeRepository) VerifyClient(ctx context.Context, clientID []byte, clientSecret string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyClient", ctx, clientID, clientSecret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyClient indicates an expected call of VerifyClient.
func (mr *MockAuthCodeRepositoryMockRecorder) VerifyClient(ctx, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyClient", reflect.TypeOf((*MockAuthCodeRepository)(nil).VerifyClient), ctx, clientID, clientSecret)
}
