// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/auth_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/auth_service.go -destination=tests/mocks/auth_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	service "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/service"
	gin "github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockAuthService) Authorize(ctx context.Context, clientIDStr, sessionToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, clientIDStr, sessionToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockAuthServiceMockRecorder) Authorize(ctx, clientIDStr, sessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAuthService)(nil).Authorize), ctx, clientIDStr, sessionToken)
}

// ExchangeCodeForToken mocks base method.
func (m *MockAuthService) ExchangeCodeForToken(ctx context.Context, req dto.TokenExchangeRequest) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCodeForToken", ctx, req)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCodeForToken indicates an expected call of ExchangeCodeForToken.
func (mr *MockAuthServiceMockRecorder) ExchangeCodeForToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCodeForToken", reflect.TypeOf((*MockAuthService)(nil).ExchangeCodeForToken), ctx, req)
}

// GetJWKS mocks base method.
func (m *MockAuthService) GetJWKS(ctx context.Context) (*service.JWKS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWKS", ctx)
	ret0, _ := ret[0].(*service.JWKS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJWKS indicates an expected call of GetJWKS.
func (mr *MockAuthServiceMockRecorder) GetJWKS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWKS", reflect.TypeOf((*MockAuthService)(nil).GetJWKS), ctx)
}

// GetSessionToken mocks base method.
func (m *MockAuthService) GetSessionToken(ctx context.Context, userID uuid.UUID, ipAddress, userAgent string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionToken", ctx, userID, ipAddress, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionToken indicates an expected call of GetSessionToken.
func (mr *MockAuthServiceMockRecorder) GetSessionToken(ctx, userID, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionToken", reflect.TypeOf((*MockAuthService)(nil).GetSessionToken), ctx, userID, ipAddress, userAgent)
}

// LoginAndAuthorize mocks base method.
func (m *MockAuthService) LoginAndAuthorize(ctx context.Context, req dto.LoginRequest, ipAddress, userAgent string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginAndAuthorize", ctx, req, ipAddress, userAgent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginAndAuthorize indicates an expected call of LoginAndAuthorize.
func (mr *MockAuthServiceMockRecorder) LoginAndAuthorize(ctx, req, ipAddress, userAgent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginAndAuthorize", reflect.TypeOf((*MockAuthService)(nil).LoginAndAuthorize), ctx, req, ipAddress, userAgent)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, sessionID)
}

// RefreshBySession mocks base method.
func (m *MockAuthService) RefreshBySession(ctx context.Context, sessionID, clientID string) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshBySession", ctx, sessionID, clientID)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshBySession indicates an expected call of RefreshBySession.
func (mr *MockAuthServiceMockRecorder) RefreshBySession(ctx, sessionID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshBySession", reflect.TypeOf((*MockAuthService)(nil).RefreshBySession), ctx, sessionID, clientID)
}

// RevokeAllUserTokens mocks base method.
func (m *MockAuthService) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserTokens indicates an expected call of RevokeAllUserTokens.
func (mr *MockAuthServiceMockRecorder) RevokeAllUserTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserTokens", reflect.TypeOf((*MockAuthService)(nil).RevokeAllUserTokens), ctx, userID)
}

// RevokeCookies mocks base method.
func (m *MockAuthService) RevokeCookies(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RevokeCookies", c)
}

// RevokeCookies indicates an expected call of RevokeCookies.
func (mr *MockAuthServiceMockRecorder) RevokeCookies(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeCookies", reflect.TypeOf((*MockAuthService)(nil).RevokeCookies), c)
}

// RotateRefreshToken mocks base method.
func (m *MockAuthService) RotateRefreshToken(ctx context.Context, oldToken string) (*dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, oldToken)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockAuthServiceMockRecorder) RotateRefreshToken(ctx, oldToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockAuthService)(nil).RotateRefreshToken), ctx, oldToken)
}

// ValidateSession mocks base method.
func (m *MockAuthService) ValidateSession(ctx context.Context, sessionID string) (*models.IdPSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionID)
	ret0, _ := ret[0].(*models.IdPSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthServiceMockRecorder) ValidateSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthService)(nil).ValidateSession), ctx, sessionID)
}
