// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/client_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/client_repository.go -destination=tests/mocks/client_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClientRepository is a mock of ClientRepository interface.
type MockClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientRepositoryMockRecorder
	isgomock struct{}
}

// MockClientRepositoryMockRecorder is the mock recorder for MockClientRepository.
type MockClientRepositoryMockRecorder struct {
	mock *MockClientRepository
}

// NewMockClientRepository creates a new mock instance.
func NewMockClientRepository(ctrl *gomock.Controller) *MockClientRepository {
	mock := &MockClientRepository{ctrl: ctrl}
	mock.recorder = &MockClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRepository) EXPECT() *MockClientRepositoryMockRecorder {
	return m.recorder
}

// AdminiClientBind mocks base method.
func (m *MockClientRepository) AdminiClientBind(ctx context.Context, userID, clientID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminiClientBind", ctx, userID, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminiClientBind indicates an expected call of AdminiClientBind.
func (mr *MockClientRepositoryMockRecorder) AdminiClientBind(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminiClientBind", reflect.TypeOf((*MockClientRepository)(nil).AdminiClientBind), ctx, userID, clientID)
}

// BatchAdminClientBind mocks base method.
func (m *MockClientRepository) BatchAdminClientBind(ctx context.Context, userID []byte, clientIDs [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAdminClientBind", ctx, userID, clientIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchAdminClientBind indicates an expected call of BatchAdminClientBind.
func (mr *MockClientRepositoryMockRecorder) BatchAdminClientBind(ctx, userID, clientIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAdminClientBind", reflect.TypeOf((*MockClientRepository)(nil).BatchAdminClientBind), ctx, userID, clientIDs)
}

// ChangeSecret mocks base method.
func (m *MockClientRepository) ChangeSecret(ctx context.Context, id []byte, newSecretHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeSecret", ctx, id, newSecretHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeSecret indicates an expected call of ChangeSecret.
func (mr *MockClientRepositoryMockRecorder) ChangeSecret(ctx, id, newSecretHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeSecret", reflect.TypeOf((*MockClientRepository)(nil).ChangeSecret), ctx, id, newSecretHash)
}

// CountAllowedClients mocks base method.
func (m *MockClientRepository) CountAllowedClients(ctx context.Context, keyword string, userID []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAllowedClients", ctx, keyword, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAllowedClients indicates an expected call of CountAllowedClients.
func (mr *MockClientRepositoryMockRecorder) CountAllowedClients(ctx, keyword, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAllowedClients", reflect.TypeOf((*MockClientRepository)(nil).CountAllowedClients), ctx, keyword, userID)
}

// CountBoundClients mocks base method.
func (m *MockClientRepository) CountBoundClients(ctx context.Context, keyword string, userID []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBoundClients", ctx, keyword, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBoundClients indicates an expected call of CountBoundClients.
func (mr *MockClientRepositoryMockRecorder) CountBoundClients(ctx, keyword, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBoundClients", reflect.TypeOf((*MockClientRepository)(nil).CountBoundClients), ctx, keyword, userID)
}

// CountClients mocks base method.
func (m *MockClientRepository) CountClients(ctx context.Context, keyword string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountClients", ctx, keyword)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountClients indicates an expected call of CountClients.
func (mr *MockClientRepositoryMockRecorder) CountClients(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountClients", reflect.TypeOf((*MockClientRepository)(nil).CountClients), ctx, keyword)
}

// CreateClient mocks base method.
func (m *MockClientRepository) CreateClient(ctx context.Context, client *models.Client, grants []string, userID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, client, grants, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientRepositoryMockRecorder) CreateClient(ctx, client, grants, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientRepository)(nil).CreateClient), ctx, client, grants, userID)
}

// DeleteAndInsertGrants mocks base method.
func (m *MockClientRepository) DeleteAndInsertGrants(ctx context.Context, c *models.Client, grants []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAndInsertGrants", ctx, c, grants)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAndInsertGrants indicates an expected call of DeleteAndInsertGrants.
func (mr *MockClientRepositoryMockRecorder) DeleteAndInsertGrants(ctx, c, grants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAndInsertGrants", reflect.TypeOf((*MockClientRepository)(nil).DeleteAndInsertGrants), ctx, c, grants)
}

// GetByID mocks base method.
func (m *MockClientRepository) GetByID(ctx context.Context, id []byte) (*models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClientRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClientRepository)(nil).GetByID), ctx, id)
}

// GetClientAllowedRoles mocks base method.
func (m *MockClientRepository) GetClientAllowedRoles(ctx context.Context, clientID []byte) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientAllowedRoles", ctx, clientID)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientAllowedRoles indicates an expected call of GetClientAllowedRoles.
func (mr *MockClientRepositoryMockRecorder) GetClientAllowedRoles(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientAllowedRoles", reflect.TypeOf((*MockClientRepository)(nil).GetClientAllowedRoles), ctx, clientID)
}

// GetGrantTypes mocks base method.
func (m *MockClientRepository) GetGrantTypes(ctx context.Context, clientID []byte) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantTypes", ctx, clientID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrantTypes indicates an expected call of GetGrantTypes.
func (mr *MockClientRepositoryMockRecorder) GetGrantTypes(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantTypes", reflect.TypeOf((*MockClientRepository)(nil).GetGrantTypes), ctx, clientID)
}

// IsClientAllowed mocks base method.
func (m *MockClientRepository) IsClientAllowed(ctx context.Context, userID, clientID []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClientAllowed", ctx, userID, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsClientAllowed indicates an expected call of IsClientAllowed.
func (mr *MockClientRepositoryMockRecorder) IsClientAllowed(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClientAllowed", reflect.TypeOf((*MockClientRepository)(nil).IsClientAllowed), ctx, userID, clientID)
}

// ListAllowedClients mocks base method.
func (m *MockClientRepository) ListAllowedClients(ctx context.Context, limit, offset int, keyword string, userID []byte) ([]models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllowedClients", ctx, limit, offset, keyword, userID)
	ret0, _ := ret[0].([]models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllowedClients indicates an expected call of ListAllowedClients.
func (mr *MockClientRepositoryMockRecorder) ListAllowedClients(ctx, limit, offset, keyword, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllowedClients", reflect.TypeOf((*MockClientRepository)(nil).ListAllowedClients), ctx, limit, offset, keyword, userID)
}

// ListBoundClients mocks base method.
func (m *MockClientRepository) ListBoundClients(ctx context.Context, limit, offset int, keyword string, userID []byte) ([]models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBoundClients", ctx, limit, offset, keyword, userID)
	ret0, _ := ret[0].([]models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBoundClients indicates an expected call of ListBoundClients.
func (mr *MockClientRepositoryMockRecorder) ListBoundClients(ctx, limit, offset, keyword, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBoundClients", reflect.TypeOf((*MockClientRepository)(nil).ListBoundClients), ctx, limit, offset, keyword, userID)
}

// ListClientBaseURLS mocks base method.
func (m *MockClientRepository) ListClientBaseURLS(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClientBaseURLS", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClientBaseURLS indicates an expected call of ListClientBaseURLS.
func (mr *MockClientRepositoryMockRecorder) ListClientBaseURLS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClientBaseURLS", reflect.TypeOf((*MockClientRepository)(nil).ListClientBaseURLS), ctx)
}

// ListClients mocks base method.
func (m *MockClientRepository) ListClients(ctx context.Context, limit, offset int, keyword string) ([]models.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClients", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]models.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClients indicates an expected call of ListClients.
func (mr *MockClientRepositoryMockRecorder) ListClients(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClients", reflect.TypeOf((*MockClientRepository)(nil).ListClients), ctx, limit, offset, keyword)
}

// RemoveAdminClientBind mocks base method.
func (m *MockClientRepository) RemoveAdminClientBind(ctx context.Context, clientID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAdminClientBind", ctx, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAdminClientBind indicates an expected call of RemoveAdminClientBind.
func (mr *MockClientRepositoryMockRecorder) RemoveAdminClientBind(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAdminClientBind", reflect.TypeOf((*MockClientRepository)(nil).RemoveAdminClientBind), ctx, clientID)
}

// RotateSecret mocks base method.
func (m *MockClientRepository) RotateSecret(ctx context.Context, id []byte, oldSecretHash, newSecretHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSecret", ctx, id, oldSecretHash, newSecretHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateSecret indicates an expected call of RotateSecret.
func (mr *MockClientRepositoryMockRecorder) RotateSecret(ctx, id, oldSecretHash, newSecretHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSecret", reflect.TypeOf((*MockClientRepository)(nil).RotateSecret), ctx, id, oldSecretHash, newSecretHash)
}

// SoftDelete mocks base method.
func (m *MockClientRepository) SoftDelete(ctx context.Context, id []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockClientRepositoryMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockClientRepository)(nil).SoftDelete), ctx, id)
}

// UpdateClient mocks base method.
func (m *MockClientRepository) UpdateClient(ctx context.Context, c *models.Client, grants []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", ctx, c, grants)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockClientRepositoryMockRecorder) UpdateClient(ctx, c, grants any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockClientRepository)(nil).UpdateClient), ctx, c, grants)
}
