// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/client_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/client_service.go -destination=tests/mocks/client_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockClientService is a mock of ClientService interface.
type MockClientService struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceMockRecorder
	isgomock struct{}
}

// MockClientServiceMockRecorder is the mock recorder for MockClientService.
type MockClientServiceMockRecorder struct {
	mock *MockClientService
}

// NewMockClientService creates a new mock instance.
func NewMockClientService(ctrl *gomock.Controller) *MockClientService {
	mock := &MockClientService{ctrl: ctrl}
	mock.recorder = &MockClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientService) EXPECT() *MockClientServiceMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockClientService) CreateClient(ctx context.Context, req dto.CreateClientRequest, image multipart.File, imageHeader *multipart.FileHeader, userID uuid.UUID) (*dto.ClientSecretResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, req, image, imageHeader, userID)
	ret0, _ := ret[0].(*dto.ClientSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockClientServiceMockRecorder) CreateClient(ctx, req, image, imageHeader, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockClientService)(nil).CreateClient), ctx, req, image, imageHeader, userID)
}

// DeleteClient mocks base method.
func (m *MockClientService) DeleteClient(ctx context.Context, id, userID uuid.UUID, permissions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", ctx, id, userID, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockClientServiceMockRecorder) DeleteClient(ctx, id, userID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockClientService)(nil).DeleteClient), ctx, id, userID, permissions)
}

// GetAllowedClients mocks base method.
func (m *MockClientService) GetAllowedClients(ctx context.Context, userID uuid.UUID, limit, page int, keyword string) (*dto.ClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedClients", ctx, userID, limit, page, keyword)
	ret0, _ := ret[0].(*dto.ClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedClients indicates an expected call of GetAllowedClients.
func (mr *MockClientServiceMockRecorder) GetAllowedClients(ctx, userID, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedClients", reflect.TypeOf((*MockClientService)(nil).GetAllowedClients), ctx, userID, limit, page, keyword)
}

// GetBoundClients mocks base method.
func (m *MockClientService) GetBoundClients(ctx context.Context, userID uuid.UUID, limit, page int, keyword string) (*dto.ClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundClients", ctx, userID, limit, page, keyword)
	ret0, _ := ret[0].(*dto.ClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundClients indicates an expected call of GetBoundClients.
func (mr *MockClientServiceMockRecorder) GetBoundClients(ctx, userID, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundClients", reflect.TypeOf((*MockClientService)(nil).GetBoundClients), ctx, userID, limit, page, keyword)
}

// GetClientByID mocks base method.
func (m *MockClientService) GetClientByID(ctx context.Context, id, userID uuid.UUID, permissions []string) (*dto.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientByID", ctx, id, userID, permissions)
	ret0, _ := ret[0].(*dto.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientByID indicates an expected call of GetClientByID.
func (mr *MockClientServiceMockRecorder) GetClientByID(ctx, id, userID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientByID", reflect.TypeOf((*MockClientService)(nil).GetClientByID), ctx, id, userID, permissions)
}

// GetClientList mocks base method.
func (m *MockClientService) GetClientList(ctx context.Context, limit, page int, keyword string) (*dto.ClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientList", ctx, limit, page, keyword)
	ret0, _ := ret[0].(*dto.ClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientList indicates an expected call of GetClientList.
func (mr *MockClientServiceMockRecorder) GetClientList(ctx, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientList", reflect.TypeOf((*MockClientService)(nil).GetClientList), ctx, limit, page, keyword)
}

// GetFilteredClientList mocks base method.
func (m *MockClientService) GetFilteredClientList(ctx context.Context, permissions []string, userID uuid.UUID, limit, page int, keyword string) (*dto.ClientListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredClientList", ctx, permissions, userID, limit, page, keyword)
	ret0, _ := ret[0].(*dto.ClientListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredClientList indicates an expected call of GetFilteredClientList.
func (mr *MockClientServiceMockRecorder) GetFilteredClientList(ctx, permissions, userID, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredClientList", reflect.TypeOf((*MockClientService)(nil).GetFilteredClientList), ctx, permissions, userID, limit, page, keyword)
}

// RotateClientSecret mocks base method.
func (m *MockClientService) RotateClientSecret(ctx context.Context, id, userID uuid.UUID, permissions []string) (*dto.ClientSecretResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateClientSecret", ctx, id, userID, permissions)
	ret0, _ := ret[0].(*dto.ClientSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateClientSecret indicates an expected call of RotateClientSecret.
func (mr *MockClientServiceMockRecorder) RotateClientSecret(ctx, id, userID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateClientSecret", reflect.TypeOf((*MockClientService)(nil).RotateClientSecret), ctx, id, userID, permissions)
}

// UpdateClient mocks base method.
func (m *MockClientService) UpdateClient(ctx context.Context, id uuid.UUID, req dto.CreateClientRequest, file multipart.File, header *multipart.FileHeader, userID uuid.UUID, permissions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", ctx, id, req, file, header, userID, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockClientServiceMockRecorder) UpdateClient(ctx, id, req, file, header, userID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockClientService)(nil).UpdateClient), ctx, id, req, file, header, userID, permissions)
}
