// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/client_allowed_user_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/client_allowed_user_service.go -destination=tests/mocks/client_allowed_user_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClientAllowedUserService is a mock of ClientAllowedUserService interface.
type MockClientAllowedUserService struct {
	ctrl     *gomock.Controller
	recorder *MockClientAllowedUserServiceMockRecorder
	isgomock struct{}
}

// MockClientAllowedUserServiceMockRecorder is the mock recorder for MockClientAllowedUserService.
type MockClientAllowedUserServiceMockRecorder struct {
	mock *MockClientAllowedUserService
}

// NewMockClientAllowedUserService creates a new mock instance.
func NewMockClientAllowedUserService(ctrl *gomock.Controller) *MockClientAllowedUserService {
	mock := &MockClientAllowedUserService{ctrl: ctrl}
	mock.recorder = &MockClientAllowedUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAllowedUserService) EXPECT() *MockClientAllowedUserServiceMockRecorder {
	return m.recorder
}

// GetAllMappings mocks base method.
func (m *MockClientAllowedUserService) GetAllMappings(ctx context.Context) ([]models.ClientAllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMappings", ctx)
	ret0, _ := ret[0].([]models.ClientAllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMappings indicates an expected call of GetAllMappings.
func (mr *MockClientAllowedUserServiceMockRecorder) GetAllMappings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMappings", reflect.TypeOf((*MockClientAllowedUserService)(nil).GetAllMappings), ctx)
}

// GetMappingsByAdmin mocks base method.
func (m *MockClientAllowedUserService) GetMappingsByAdmin(ctx context.Context, adminID []byte) ([]models.ClientAllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMappingsByAdmin", ctx, adminID)
	ret0, _ := ret[0].([]models.ClientAllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMappingsByAdmin indicates an expected call of GetMappingsByAdmin.
func (mr *MockClientAllowedUserServiceMockRecorder) GetMappingsByAdmin(ctx, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMappingsByAdmin", reflect.TypeOf((*MockClientAllowedUserService)(nil).GetMappingsByAdmin), ctx, adminID)
}

// SyncAccess mocks base method.
func (m *MockClientAllowedUserService) SyncAccess(ctx context.Context, userID []byte, clientIDs [][]byte, adminID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAccess", ctx, userID, clientIDs, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncAccess indicates an expected call of SyncAccess.
func (mr *MockClientAllowedUserServiceMockRecorder) SyncAccess(ctx, userID, clientIDs, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAccess", reflect.TypeOf((*MockClientAllowedUserService)(nil).SyncAccess), ctx, userID, clientIDs, adminID)
}
