// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/client_allowed_user_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/client_allowed_user_repository.go -destination=tests/mocks/client_allowed_user_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClientAllowedUserRepository is a mock of ClientAllowedUserRepository interface.
type MockClientAllowedUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientAllowedUserRepositoryMockRecorder
	isgomock struct{}
}

// MockClientAllowedUserRepositoryMockRecorder is the mock recorder for MockClientAllowedUserRepository.
type MockClientAllowedUserRepositoryMockRecorder struct {
	mock *MockClientAllowedUserRepository
}

// NewMockClientAllowedUserRepository creates a new mock instance.
func NewMockClientAllowedUserRepository(ctrl *gomock.Controller) *MockClientAllowedUserRepository {
	mock := &MockClientAllowedUserRepository{ctrl: ctrl}
	mock.recorder = &MockClientAllowedUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAllowedUserRepository) EXPECT() *MockClientAllowedUserRepositoryMockRecorder {
	return m.recorder
}

// AssignClientAccess mocks base method.
func (m *MockClientAllowedUserRepository) AssignClientAccess(ctx context.Context, userID, clientID []byte, source models.AssignmentSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignClientAccess", ctx, userID, clientID, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignClientAccess indicates an expected call of AssignClientAccess.
func (mr *MockClientAllowedUserRepositoryMockRecorder) AssignClientAccess(ctx, userID, clientID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignClientAccess", reflect.TypeOf((*MockClientAllowedUserRepository)(nil).AssignClientAccess), ctx, userID, clientID, source)
}

// BatchAssignClientAccess mocks base method.
func (m *MockClientAllowedUserRepository) BatchAssignClientAccess(ctx context.Context, userID []byte, clientIDs [][]byte, source models.AssignmentSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAssignClientAccess", ctx, userID, clientIDs, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchAssignClientAccess indicates an expected call of BatchAssignClientAccess.
func (mr *MockClientAllowedUserRepositoryMockRecorder) BatchAssignClientAccess(ctx, userID, clientIDs, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAssignClientAccess", reflect.TypeOf((*MockClientAllowedUserRepository)(nil).BatchAssignClientAccess), ctx, userID, clientIDs, source)
}

// GetAll mocks base method.
func (m *MockClientAllowedUserRepository) GetAll(ctx context.Context) ([]models.ClientAllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.ClientAllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockClientAllowedUserRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockClientAllowedUserRepository)(nil).GetAll), ctx)
}

// GetByAdmin mocks base method.
func (m *MockClientAllowedUserRepository) GetByAdmin(ctx context.Context, adminID []byte) ([]models.ClientAllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAdmin", ctx, adminID)
	ret0, _ := ret[0].([]models.ClientAllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAdmin indicates an expected call of GetByAdmin.
func (mr *MockClientAllowedUserRepositoryMockRecorder) GetByAdmin(ctx, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAdmin", reflect.TypeOf((*MockClientAllowedUserRepository)(nil).GetByAdmin), ctx, adminID)
}

// SyncPreapprovedUserAccess mocks base method.
func (m *MockClientAllowedUserRepository) SyncPreapprovedUserAccess(ctx context.Context, userID []byte, clientIDs [][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPreapprovedUserAccess", ctx, userID, clientIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncPreapprovedUserAccess indicates an expected call of SyncPreapprovedUserAccess.
func (mr *MockClientAllowedUserRepositoryMockRecorder) SyncPreapprovedUserAccess(ctx, userID, clientIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPreapprovedUserAccess", reflect.TypeOf((*MockClientAllowedUserRepository)(nil).SyncPreapprovedUserAccess), ctx, userID, clientIDs)
}

// SyncUserAccess mocks base method.
func (m *MockClientAllowedUserRepository) SyncUserAccess(ctx context.Context, userID []byte, clientIDs [][]byte, adminID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUserAccess", ctx, userID, clientIDs, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncUserAccess indicates an expected call of SyncUserAccess.
func (mr *MockClientAllowedUserRepositoryMockRecorder) SyncUserAccess(ctx, userID, clientIDs, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUserAccess", reflect.TypeOf((*MockClientAllowedUserRepository)(nil).SyncUserAccess), ctx, userID, clientIDs, adminID)
}
