// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/device_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/device_service.go -destination=tests/mocks/device_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceService is a mock of DeviceService interface.
type MockDeviceService struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceServiceMockRecorder
	isgomock struct{}
}

// MockDeviceServiceMockRecorder is the mock recorder for MockDeviceService.
type MockDeviceServiceMockRecorder struct {
	mock *MockDeviceService
}

// NewMockDeviceService creates a new mock instance.
func NewMockDeviceService(ctrl *gomock.Controller) *MockDeviceService {
	mock := &MockDeviceService{ctrl: ctrl}
	mock.recorder = &MockDeviceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceService) EXPECT() *MockDeviceServiceMockRecorder {
	return m.recorder
}

// DeleteDevice mocks base method.
func (m *MockDeviceService) DeleteDevice(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockDeviceServiceMockRecorder) DeleteDevice(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockDeviceService)(nil).DeleteDevice), ctx, id, userID)
}

// ListDevices mocks base method.
func (m *MockDeviceService) ListDevices(ctx context.Context, userID uuid.UUID) ([]dto.UserDeviceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", ctx, userID)
	ret0, _ := ret[0].([]dto.UserDeviceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockDeviceServiceMockRecorder) ListDevices(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockDeviceService)(nil).ListDevices), ctx, userID)
}

// RegisterDevice mocks base method.
func (m *MockDeviceService) RegisterDevice(ctx context.Context, userID uuid.UUID, ip, ua string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDevice", ctx, userID, ip, ua)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterDevice indicates an expected call of RegisterDevice.
func (mr *MockDeviceServiceMockRecorder) RegisterDevice(ctx, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDevice", reflect.TypeOf((*MockDeviceService)(nil).RegisterDevice), ctx, userID, ip, ua)
}

// UpdateDeviceName mocks base method.
func (m *MockDeviceService) UpdateDeviceName(ctx context.Context, id, userID uuid.UUID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceName", ctx, id, userID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceName indicates an expected call of UpdateDeviceName.
func (mr *MockDeviceServiceMockRecorder) UpdateDeviceName(ctx, id, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceName", reflect.TypeOf((*MockDeviceService)(nil).UpdateDeviceName), ctx, id, userID, name)
}

// VerifyDevice mocks base method.
func (m *MockDeviceService) VerifyDevice(ctx context.Context, userID uuid.UUID, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDevice", ctx, userID, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyDevice indicates an expected call of VerifyDevice.
func (mr *MockDeviceServiceMockRecorder) VerifyDevice(ctx, userID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDevice", reflect.TypeOf((*MockDeviceService)(nil).VerifyDevice), ctx, userID, token)
}
