// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/invitation_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/invitation_repository.go -destination=tests/mocks/invitation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInvitationRepository is a mock of InvitationRepository interface.
type MockInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationRepositoryMockRecorder
	isgomock struct{}
}

// MockInvitationRepositoryMockRecorder is the mock recorder for MockInvitationRepository.
type MockInvitationRepositoryMockRecorder struct {
	mock *MockInvitationRepository
}

// NewMockInvitationRepository creates a new mock instance.
func NewMockInvitationRepository(ctrl *gomock.Controller) *MockInvitationRepository {
	mock := &MockInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationRepository) EXPECT() *MockInvitationRepositoryMockRecorder {
	return m.recorder
}

// CreateInvitation mocks base method.
func (m *MockInvitationRepository) CreateInvitation(ctx context.Context, inv *models.InvitationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockInvitationRepositoryMockRecorder) CreateInvitation(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockInvitationRepository)(nil).CreateInvitation), ctx, inv)
}

// DeleteInvitation mocks base method.
func (m *MockInvitationRepository) DeleteInvitation(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitation", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitation indicates an expected call of DeleteInvitation.
func (mr *MockInvitationRepositoryMockRecorder) DeleteInvitation(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitation", reflect.TypeOf((*MockInvitationRepository)(nil).DeleteInvitation), ctx, email)
}

// GetAccountTypeIDByInvitationCode mocks base method.
func (m *MockInvitationRepository) GetAccountTypeIDByInvitationCode(ctx context.Context, code string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeIDByInvitationCode", ctx, code)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeIDByInvitationCode indicates an expected call of GetAccountTypeIDByInvitationCode.
func (mr *MockInvitationRepositoryMockRecorder) GetAccountTypeIDByInvitationCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeIDByInvitationCode", reflect.TypeOf((*MockInvitationRepository)(nil).GetAccountTypeIDByInvitationCode), ctx, code)
}

// GetInvitationByCode mocks base method.
func (m *MockInvitationRepository) GetInvitationByCode(ctx context.Context, code string) (*models.InvitationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitationByCode", ctx, code)
	ret0, _ := ret[0].(*models.InvitationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitationByCode indicates an expected call of GetInvitationByCode.
func (mr *MockInvitationRepositoryMockRecorder) GetInvitationByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitationByCode", reflect.TypeOf((*MockInvitationRepository)(nil).GetInvitationByCode), ctx, code)
}

// GetInvitationByEmail mocks base method.
func (m *MockInvitationRepository) GetInvitationByEmail(ctx context.Context, email string) (*models.InvitationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitationByEmail", ctx, email)
	ret0, _ := ret[0].(*models.InvitationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitationByEmail indicates an expected call of GetInvitationByEmail.
func (mr *MockInvitationRepositoryMockRecorder) GetInvitationByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitationByEmail", reflect.TypeOf((*MockInvitationRepository)(nil).GetInvitationByEmail), ctx, email)
}
