// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/log_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/log_service.go -destination=tests/mocks/log_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockLogService is a mock of LogService interface.
type MockLogService struct {
	ctrl     *gomock.Controller
	recorder *MockLogServiceMockRecorder
	isgomock struct{}
}

// MockLogServiceMockRecorder is the mock recorder for MockLogService.
type MockLogServiceMockRecorder struct {
	mock *MockLogService
}

// NewMockLogService creates a new mock instance.
func NewMockLogService(ctrl *gomock.Controller) *MockLogService {
	mock := &MockLogService{ctrl: ctrl}
	mock.recorder = &MockLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogService) EXPECT() *MockLogServiceMockRecorder {
	return m.recorder
}

// GetLog mocks base method.
func (m *MockLogService) GetLog(ctx context.Context, req *dto.GetAuditLogRequest) (*dto.PostAuditLogRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", ctx, req)
	ret0, _ := ret[0].(*dto.PostAuditLogRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLog indicates an expected call of GetLog.
func (mr *MockLogServiceMockRecorder) GetLog(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockLogService)(nil).GetLog), ctx, req)
}

// GetLogByID mocks base method.
func (m *MockLogService) GetLogByID(ctx context.Context, id int64) (*dto.PostAuditLogRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogByID", ctx, id)
	ret0, _ := ret[0].(*dto.PostAuditLogRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogByID indicates an expected call of GetLogByID.
func (mr *MockLogServiceMockRecorder) GetLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogByID", reflect.TypeOf((*MockLogService)(nil).GetLogByID), ctx, id)
}

// GetLogList mocks base method.
func (m *MockLogService) GetLogList(ctx context.Context, limit, offset int) ([]dto.PostAuditLogRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogList", ctx, limit, offset)
	ret0, _ := ret[0].([]dto.PostAuditLogRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogList indicates an expected call of GetLogList.
func (mr *MockLogServiceMockRecorder) GetLogList(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogList", reflect.TypeOf((*MockLogService)(nil).GetLogList), ctx, limit, offset)
}

// GetLogListWithFilters mocks base method.
func (m *MockLogService) GetLogListWithFilters(ctx context.Context, filters map[string]any, limit, page int) ([]dto.PostAuditLogRequest, int64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogListWithFilters", ctx, filters, limit, page)
	ret0, _ := ret[0].([]dto.PostAuditLogRequest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetLogListWithFilters indicates an expected call of GetLogListWithFilters.
func (mr *MockLogServiceMockRecorder) GetLogListWithFilters(ctx, filters, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogListWithFilters", reflect.TypeOf((*MockLogService)(nil).GetLogListWithFilters), ctx, filters, limit, page)
}

// GetSecurityLog mocks base method.
func (m *MockLogService) GetSecurityLog(ctx context.Context, req *dto.GetAuditLogRequest) (*dto.PostAuditLogRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLog", ctx, req)
	ret0, _ := ret[0].(*dto.PostAuditLogRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityLog indicates an expected call of GetSecurityLog.
func (mr *MockLogServiceMockRecorder) GetSecurityLog(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLog", reflect.TypeOf((*MockLogService)(nil).GetSecurityLog), ctx, req)
}

// GetSecurityLogByID mocks base method.
func (m *MockLogService) GetSecurityLogByID(ctx context.Context, id int64) (*dto.PostAuditLogRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLogByID", ctx, id)
	ret0, _ := ret[0].(*dto.PostAuditLogRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityLogByID indicates an expected call of GetSecurityLogByID.
func (mr *MockLogServiceMockRecorder) GetSecurityLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLogByID", reflect.TypeOf((*MockLogService)(nil).GetSecurityLogByID), ctx, id)
}

// GetSecurityLogListWithFilters mocks base method.
func (m *MockLogService) GetSecurityLogListWithFilters(ctx context.Context, filters map[string]any, limit, page int) ([]dto.PostAuditLogRequest, int64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLogListWithFilters", ctx, filters, limit, page)
	ret0, _ := ret[0].([]dto.PostAuditLogRequest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetSecurityLogListWithFilters indicates an expected call of GetSecurityLogListWithFilters.
func (mr *MockLogServiceMockRecorder) GetSecurityLogListWithFilters(ctx, filters, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLogListWithFilters", reflect.TypeOf((*MockLogService)(nil).GetSecurityLogListWithFilters), ctx, filters, limit, page)
}

// GetUserEmail mocks base method.
func (m *MockLogService) GetUserEmail(ctx context.Context, userID []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmail", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmail indicates an expected call of GetUserEmail.
func (mr *MockLogServiceMockRecorder) GetUserEmail(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmail", reflect.TypeOf((*MockLogService)(nil).GetUserEmail), ctx, userID)
}

// PostAuditLog mocks base method.
func (m *MockLogService) PostAuditLog(ctx context.Context, actorID []byte, req *dto.PostAuditLogRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostAuditLog", ctx, actorID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostAuditLog indicates an expected call of PostAuditLog.
func (mr *MockLogServiceMockRecorder) PostAuditLog(ctx, actorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostAuditLog", reflect.TypeOf((*MockLogService)(nil).PostAuditLog), ctx, actorID, req)
}

// PostAuditLogWithActorString mocks base method.
func (m *MockLogService) PostAuditLogWithActorString(ctx context.Context, actor string, req *dto.PostAuditLogRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostAuditLogWithActorString", ctx, actor, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostAuditLogWithActorString indicates an expected call of PostAuditLogWithActorString.
func (mr *MockLogServiceMockRecorder) PostAuditLogWithActorString(ctx, actor, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostAuditLogWithActorString", reflect.TypeOf((*MockLogService)(nil).PostAuditLogWithActorString), ctx, actor, req)
}

// PostSecurityLog mocks base method.
func (m *MockLogService) PostSecurityLog(ctx context.Context, actorID []byte, req *dto.PostAuditLogRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSecurityLog", ctx, actorID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostSecurityLog indicates an expected call of PostSecurityLog.
func (mr *MockLogServiceMockRecorder) PostSecurityLog(ctx, actorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSecurityLog", reflect.TypeOf((*MockLogService)(nil).PostSecurityLog), ctx, actorID, req)
}

// PostSecurityLogWithActorString mocks base method.
func (m *MockLogService) PostSecurityLogWithActorString(ctx context.Context, actor string, req *dto.PostAuditLogRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSecurityLogWithActorString", ctx, actor, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostSecurityLogWithActorString indicates an expected call of PostSecurityLogWithActorString.
func (mr *MockLogServiceMockRecorder) PostSecurityLogWithActorString(ctx, actor, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSecurityLogWithActorString", reflect.TypeOf((*MockLogService)(nil).PostSecurityLogWithActorString), ctx, actor, req)
}

// ResolveClientName mocks base method.
func (m *MockLogService) ResolveClientName(ctx context.Context, clientID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveClientName", ctx, clientID)
	ret0, _ := ret[0].(string)
	return ret0
}

// ResolveClientName indicates an expected call of ResolveClientName.
func (mr *MockLogServiceMockRecorder) ResolveClientName(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveClientName", reflect.TypeOf((*MockLogService)(nil).ResolveClientName), ctx, clientID)
}
