// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/log_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/log_repository.go -destination=tests/mocks/log_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLogRepository is a mock of LogRepository interface.
type MockLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogRepositoryMockRecorder
	isgomock struct{}
}

// MockLogRepositoryMockRecorder is the mock recorder for MockLogRepository.
type MockLogRepositoryMockRecorder struct {
	mock *MockLogRepository
}

// NewMockLogRepository creates a new mock instance.
func NewMockLogRepository(ctrl *gomock.Controller) *MockLogRepository {
	mock := &MockLogRepository{ctrl: ctrl}
	mock.recorder = &MockLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogRepository) EXPECT() *MockLogRepositoryMockRecorder {
	return m.recorder
}

// CreateLog mocks base method.
func (m *MockLogRepository) CreateLog(ctx context.Context, log *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLog indicates an expected call of CreateLog.
func (mr *MockLogRepositoryMockRecorder) CreateLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLog", reflect.TypeOf((*MockLogRepository)(nil).CreateLog), ctx, log)
}

// CreateSecurityLog mocks base method.
func (m *MockLogRepository) CreateSecurityLog(ctx context.Context, log *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecurityLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecurityLog indicates an expected call of CreateSecurityLog.
func (mr *MockLogRepositoryMockRecorder) CreateSecurityLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecurityLog", reflect.TypeOf((*MockLogRepository)(nil).CreateSecurityLog), ctx, log)
}

// GetClientNameByID mocks base method.
func (m *MockLogRepository) GetClientNameByID(ctx context.Context, clientID []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientNameByID", ctx, clientID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientNameByID indicates an expected call of GetClientNameByID.
func (mr *MockLogRepositoryMockRecorder) GetClientNameByID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientNameByID", reflect.TypeOf((*MockLogRepository)(nil).GetClientNameByID), ctx, clientID)
}

// GetLog mocks base method.
func (m *MockLogRepository) GetLog(ctx context.Context, actor *string, status string) (*models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", ctx, actor, status)
	ret0, _ := ret[0].(*models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLog indicates an expected call of GetLog.
func (mr *MockLogRepositoryMockRecorder) GetLog(ctx, actor, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockLogRepository)(nil).GetLog), ctx, actor, status)
}

// GetLogByID mocks base method.
func (m *MockLogRepository) GetLogByID(ctx context.Context, id int64) (*models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogByID", ctx, id)
	ret0, _ := ret[0].(*models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogByID indicates an expected call of GetLogByID.
func (mr *MockLogRepositoryMockRecorder) GetLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogByID", reflect.TypeOf((*MockLogRepository)(nil).GetLogByID), ctx, id)
}

// GetLogList mocks base method.
func (m *MockLogRepository) GetLogList(ctx context.Context, limit, offset int) ([]models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogList", ctx, limit, offset)
	ret0, _ := ret[0].([]models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogList indicates an expected call of GetLogList.
func (mr *MockLogRepositoryMockRecorder) GetLogList(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogList", reflect.TypeOf((*MockLogRepository)(nil).GetLogList), ctx, limit, offset)
}

// GetLogListWithFilters mocks base method.
func (m *MockLogRepository) GetLogListWithFilters(ctx context.Context, filters map[string]any, limit, offset int) ([]models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogListWithFilters", ctx, filters, limit, offset)
	ret0, _ := ret[0].([]models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLogListWithFilters indicates an expected call of GetLogListWithFilters.
func (mr *MockLogRepositoryMockRecorder) GetLogListWithFilters(ctx, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogListWithFilters", reflect.TypeOf((*MockLogRepository)(nil).GetLogListWithFilters), ctx, filters, limit, offset)
}

// GetSecurityLog mocks base method.
func (m *MockLogRepository) GetSecurityLog(ctx context.Context, actor *string, status string) (*models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLog", ctx, actor, status)
	ret0, _ := ret[0].(*models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityLog indicates an expected call of GetSecurityLog.
func (mr *MockLogRepositoryMockRecorder) GetSecurityLog(ctx, actor, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLog", reflect.TypeOf((*MockLogRepository)(nil).GetSecurityLog), ctx, actor, status)
}

// GetSecurityLogByID mocks base method.
func (m *MockLogRepository) GetSecurityLogByID(ctx context.Context, id int64) (*models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLogByID", ctx, id)
	ret0, _ := ret[0].(*models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityLogByID indicates an expected call of GetSecurityLogByID.
func (mr *MockLogRepositoryMockRecorder) GetSecurityLogByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLogByID", reflect.TypeOf((*MockLogRepository)(nil).GetSecurityLogByID), ctx, id)
}

// GetSecurityLogList mocks base method.
func (m *MockLogRepository) GetSecurityLogList(ctx context.Context, limit, offset int) ([]models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLogList", ctx, limit, offset)
	ret0, _ := ret[0].([]models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecurityLogList indicates an expected call of GetSecurityLogList.
func (mr *MockLogRepositoryMockRecorder) GetSecurityLogList(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLogList", reflect.TypeOf((*MockLogRepository)(nil).GetSecurityLogList), ctx, limit, offset)
}

// GetSecurityLogListWithFilters mocks base method.
func (m *MockLogRepository) GetSecurityLogListWithFilters(ctx context.Context, filters map[string]any, limit, offset int) ([]models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecurityLogListWithFilters", ctx, filters, limit, offset)
	ret0, _ := ret[0].([]models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSecurityLogListWithFilters indicates an expected call of GetSecurityLogListWithFilters.
func (mr *MockLogRepositoryMockRecorder) GetSecurityLogListWithFilters(ctx, filters, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecurityLogListWithFilters", reflect.TypeOf((*MockLogRepository)(nil).GetSecurityLogListWithFilters), ctx, filters, limit, offset)
}

// GetUserEmailbyID mocks base method.
func (m *MockLogRepository) GetUserEmailbyID(ctx context.Context, userID []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmailbyID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmailbyID indicates an expected call of GetUserEmailbyID.
func (mr *MockLogRepositoryMockRecorder) GetUserEmailbyID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmailbyID", reflect.TypeOf((*MockLogRepository)(nil).GetUserEmailbyID), ctx, userID)
}
