// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/mail_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/mail_service.go -destination=tests/mocks/mail_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailService is a mock of MailService interface.
type MockMailService struct {
	ctrl     *gomock.Controller
	recorder *MockMailServiceMockRecorder
	isgomock struct{}
}

// MockMailServiceMockRecorder is the mock recorder for MockMailService.
type MockMailServiceMockRecorder struct {
	mock *MockMailService
}

// NewMockMailService creates a new mock instance.
func NewMockMailService(ctrl *gomock.Controller) *MockMailService {
	mock := &MockMailService{ctrl: ctrl}
	mock.recorder = &MockMailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailService) EXPECT() *MockMailServiceMockRecorder {
	return m.recorder
}

// SendAndSaveInvitation mocks base method.
func (m *MockMailService) SendAndSaveInvitation(ctx context.Context, email string, accountTypeID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndSaveInvitation", ctx, email, accountTypeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndSaveInvitation indicates an expected call of SendAndSaveInvitation.
func (mr *MockMailServiceMockRecorder) SendAndSaveInvitation(ctx, email, accountTypeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndSaveInvitation", reflect.TypeOf((*MockMailService)(nil).SendAndSaveInvitation), ctx, email, accountTypeID)
}

// SendAndSaveOTP mocks base method.
func (m *MockMailService) SendAndSaveOTP(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndSaveOTP", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndSaveOTP indicates an expected call of SendAndSaveOTP.
func (mr *MockMailServiceMockRecorder) SendAndSaveOTP(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndSaveOTP", reflect.TypeOf((*MockMailService)(nil).SendAndSaveOTP), ctx, email)
}
