// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/media.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/media.go -destination=tests/mocks/media_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
