// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/metrics_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/metrics_repository.go -destination=tests/mocks/metrics_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRepository is a mock of MetricsRepository interface.
type MockMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricsRepositoryMockRecorder is the mock recorder for MockMetricsRepository.
type MockMetricsRepositoryMockRecorder struct {
	mock *MockMetricsRepository
}

// NewMockMetricsRepository creates a new mock instance.
func NewMockMetricsRepository(ctrl *gomock.Controller) *MockMetricsRepository {
	mock := &MockMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRepository) EXPECT() *MockMetricsRepositoryMockRecorder {
	return m.recorder
}

// GetBoundClientIDs mocks base method.
func (m *MockMetricsRepository) GetBoundClientIDs(ctx context.Context, userID []byte) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundClientIDs", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundClientIDs indicates an expected call of GetBoundClientIDs.
func (mr *MockMetricsRepositoryMockRecorder) GetBoundClientIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundClientIDs", reflect.TypeOf((*MockMetricsRepository)(nil).GetBoundClientIDs), ctx, userID)
}

// GetClientMetrics mocks base method.
func (m *MockMetricsRepository) GetClientMetrics(ctx context.Context, allowedClients []string) ([]models.MetricCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientMetrics", ctx, allowedClients)
	ret0, _ := ret[0].([]models.MetricCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientMetrics indicates an expected call of GetClientMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetClientMetrics(ctx, allowedClients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetClientMetrics), ctx, allowedClients)
}

// GetFailedAuthAttempts mocks base method.
func (m *MockMetricsRepository) GetFailedAuthAttempts(ctx context.Context, since time.Time, allowedClients []string) ([]models.FailedAuthAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFailedAuthAttempts", ctx, since, allowedClients)
	ret0, _ := ret[0].([]models.FailedAuthAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailedAuthAttempts indicates an expected call of GetFailedAuthAttempts.
func (mr *MockMetricsRepositoryMockRecorder) GetFailedAuthAttempts(ctx, since, allowedClients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFailedAuthAttempts", reflect.TypeOf((*MockMetricsRepository)(nil).GetFailedAuthAttempts), ctx, since, allowedClients)
}

// GetLogMetrics mocks base method.
func (m *MockMetricsRepository) GetLogMetrics(ctx context.Context, hasAudit, hasSecurity bool) ([]models.MetricCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogMetrics", ctx, hasAudit, hasSecurity)
	ret0, _ := ret[0].([]models.MetricCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogMetrics indicates an expected call of GetLogMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetLogMetrics(ctx, hasAudit, hasSecurity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetLogMetrics), ctx, hasAudit, hasSecurity)
}

// GetPaginatedLogins mocks base method.
func (m *MockMetricsRepository) GetPaginatedLogins(ctx context.Context, since time.Time, limit, offset int, adminID []byte) ([]models.AuditLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaginatedLogins", ctx, since, limit, offset, adminID)
	ret0, _ := ret[0].([]models.AuditLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPaginatedLogins indicates an expected call of GetPaginatedLogins.
func (mr *MockMetricsRepositoryMockRecorder) GetPaginatedLogins(ctx, since, limit, offset, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaginatedLogins", reflect.TypeOf((*MockMetricsRepository)(nil).GetPaginatedLogins), ctx, since, limit, offset, adminID)
}

// GetPermissionMetrics mocks base method.
func (m *MockMetricsRepository) GetPermissionMetrics(ctx context.Context) ([]models.MetricCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionMetrics", ctx)
	ret0, _ := ret[0].([]models.MetricCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionMetrics indicates an expected call of GetPermissionMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetPermissionMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetPermissionMetrics), ctx)
}

// GetRegistrationMetrics mocks base method.
func (m *MockMetricsRepository) GetRegistrationMetrics(ctx context.Context, allowedClients []string) ([]models.MetricCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationMetrics", ctx, allowedClients)
	ret0, _ := ret[0].([]models.MetricCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationMetrics indicates an expected call of GetRegistrationMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetRegistrationMetrics(ctx, allowedClients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetRegistrationMetrics), ctx, allowedClients)
}

// GetRoleMetrics mocks base method.
func (m *MockMetricsRepository) GetRoleMetrics(ctx context.Context) ([]models.MetricCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleMetrics", ctx)
	ret0, _ := ret[0].([]models.MetricCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleMetrics indicates an expected call of GetRoleMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetRoleMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetRoleMetrics), ctx)
}

// GetTopClients mocks base method.
func (m *MockMetricsRepository) GetTopClients(ctx context.Context, limit int, since time.Time, allowedClients []string) ([]models.TopClientLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopClients", ctx, limit, since, allowedClients)
	ret0, _ := ret[0].([]models.TopClientLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopClients indicates an expected call of GetTopClients.
func (mr *MockMetricsRepositoryMockRecorder) GetTopClients(ctx, limit, since, allowedClients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopClients", reflect.TypeOf((*MockMetricsRepository)(nil).GetTopClients), ctx, limit, since, allowedClients)
}

// GetTotalLogins mocks base method.
func (m *MockMetricsRepository) GetTotalLogins(ctx context.Context, since time.Time, allowedClients []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalLogins", ctx, since, allowedClients)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalLogins indicates an expected call of GetTotalLogins.
func (mr *MockMetricsRepositoryMockRecorder) GetTotalLogins(ctx, since, allowedClients any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalLogins", reflect.TypeOf((*MockMetricsRepository)(nil).GetTotalLogins), ctx, since, allowedClients)
}

// GetUserMetrics mocks base method.
func (m *MockMetricsRepository) GetUserMetrics(ctx context.Context, adminID []byte) ([]models.MetricCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMetrics", ctx, adminID)
	ret0, _ := ret[0].([]models.MetricCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMetrics indicates an expected call of GetUserMetrics.
func (mr *MockMetricsRepositoryMockRecorder) GetUserMetrics(ctx, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMetrics", reflect.TypeOf((*MockMetricsRepository)(nil).GetUserMetrics), ctx, adminID)
}
