// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/mfa_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/mfa_service.go -destination=tests/mocks/mfa_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockMFAService is a mock of MFAService interface.
type MockMFAService struct {
	ctrl     *gomock.Controller
	recorder *MockMFAServiceMockRecorder
	isgomock struct{}
}

// MockMFAServiceMockRecorder is the mock recorder for MockMFAService.
type MockMFAServiceMockRecorder struct {
	mock *MockMFAService
}

// NewMockMFAService creates a new mock instance.
func NewMockMFAService(ctrl *gomock.Controller) *MockMFAService {
	mock := &MockMFAService{ctrl: ctrl}
	mock.recorder = &MockMFAServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFAService) EXPECT() *MockMFAServiceMockRecorder {
	return m.recorder
}

// FinalizeTOTP mocks base method.
func (m *MockMFAService) FinalizeTOTP(ctx context.Context, userID []byte, secret, code, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeTOTP", ctx, userID, secret, code, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeTOTP indicates an expected call of FinalizeTOTP.
func (mr *MockMFAServiceMockRecorder) FinalizeTOTP(ctx, userID, secret, code, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeTOTP", reflect.TypeOf((*MockMFAService)(nil).FinalizeTOTP), ctx, userID, secret, code, name)
}

// GenerateTOTPSetup mocks base method.
func (m *MockMFAService) GenerateTOTPSetup(ctx context.Context, email string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTOTPSetup", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateTOTPSetup indicates an expected call of GenerateTOTPSetup.
func (mr *MockMFAServiceMockRecorder) GenerateTOTPSetup(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTOTPSetup", reflect.TypeOf((*MockMFAService)(nil).GenerateTOTPSetup), ctx, email)
}

// GetAuthenticatorList mocks base method.
func (m *MockMFAService) GetAuthenticatorList(ctx context.Context, userID []byte) ([]dto.MFAAuthenticatorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthenticatorList", ctx, userID)
	ret0, _ := ret[0].([]dto.MFAAuthenticatorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthenticatorList indicates an expected call of GetAuthenticatorList.
func (mr *MockMFAServiceMockRecorder) GetAuthenticatorList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthenticatorList", reflect.TypeOf((*MockMFAService)(nil).GetAuthenticatorList), ctx, userID)
}

// RemoveAuthenticator mocks base method.
func (m *MockMFAService) RemoveAuthenticator(ctx context.Context, id, userID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAuthenticator", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAuthenticator indicates an expected call of RemoveAuthenticator.
func (mr *MockMFAServiceMockRecorder) RemoveAuthenticator(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAuthenticator", reflect.TypeOf((*MockMFAService)(nil).RemoveAuthenticator), ctx, id, userID)
}

// SetupTOTP mocks base method.
func (m *MockMFAService) SetupTOTP(ctx context.Context, userID []byte, email string) (string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupTOTP", ctx, userID, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetupTOTP indicates an expected call of SetupTOTP.
func (mr *MockMFAServiceMockRecorder) SetupTOTP(ctx, userID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupTOTP", reflect.TypeOf((*MockMFAService)(nil).SetupTOTP), ctx, userID, email)
}

// VerifyCode mocks base method.
func (m *MockMFAService) VerifyCode(ctx context.Context, userID []byte, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, userID, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockMFAServiceMockRecorder) VerifyCode(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockMFAService)(nil).VerifyCode), ctx, userID, code)
}
