// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/mfa_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/mfa_repository.go -destination=tests/mocks/mfa_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMFARepository is a mock of MFARepository interface.
type MockMFARepository struct {
	ctrl     *gomock.Controller
	recorder *MockMFARepositoryMockRecorder
	isgomock struct{}
}

// MockMFARepositoryMockRecorder is the mock recorder for MockMFARepository.
type MockMFARepositoryMockRecorder struct {
	mock *MockMFARepository
}

// NewMockMFARepository creates a new mock instance.
func NewMockMFARepository(ctrl *gomock.Controller) *MockMFARepository {
	mock := &MockMFARepository{ctrl: ctrl}
	mock.recorder = &MockMFARepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFARepository) EXPECT() *MockMFARepositoryMockRecorder {
	return m.recorder
}

// DeleteAuthenticator mocks base method.
func (m *MockMFARepository) DeleteAuthenticator(ctx context.Context, id, userID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAuthenticator", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAuthenticator indicates an expected call of DeleteAuthenticator.
func (mr *MockMFARepositoryMockRecorder) DeleteAuthenticator(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAuthenticator", reflect.TypeOf((*MockMFARepository)(nil).DeleteAuthenticator), ctx, id, userID)
}

// GetAuthenticatorList mocks base method.
func (m *MockMFARepository) GetAuthenticatorList(ctx context.Context, userID []byte) ([]models.AuthenticatorMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthenticatorList", ctx, userID)
	ret0, _ := ret[0].([]models.AuthenticatorMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthenticatorList indicates an expected call of GetAuthenticatorList.
func (mr *MockMFARepositoryMockRecorder) GetAuthenticatorList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthenticatorList", reflect.TypeOf((*MockMFARepository)(nil).GetAuthenticatorList), ctx, userID)
}

// GetAuthenticatorsByUserIDAndType mocks base method.
func (m *MockMFARepository) GetAuthenticatorsByUserIDAndType(ctx context.Context, userID []byte, authType string) ([]models.UserAuthenticator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthenticatorsByUserIDAndType", ctx, userID, authType)
	ret0, _ := ret[0].([]models.UserAuthenticator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthenticatorsByUserIDAndType indicates an expected call of GetAuthenticatorsByUserIDAndType.
func (mr *MockMFARepositoryMockRecorder) GetAuthenticatorsByUserIDAndType(ctx, userID, authType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthenticatorsByUserIDAndType", reflect.TypeOf((*MockMFARepository)(nil).GetAuthenticatorsByUserIDAndType), ctx, userID, authType)
}

// InsertAuthenticator mocks base method.
func (m *MockMFARepository) InsertAuthenticator(ctx context.Context, auth *models.UserAuthenticator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAuthenticator", ctx, auth)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAuthenticator indicates an expected call of InsertAuthenticator.
func (mr *MockMFARepositoryMockRecorder) InsertAuthenticator(ctx, auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAuthenticator", reflect.TypeOf((*MockMFARepository)(nil).InsertAuthenticator), ctx, auth)
}

// UpdateLastUsedAt mocks base method.
func (m *MockMFARepository) UpdateLastUsedAt(ctx context.Context, id []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsedAt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsedAt indicates an expected call of UpdateLastUsedAt.
func (mr *MockMFARepositoryMockRecorder) UpdateLastUsedAt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsedAt", reflect.TypeOf((*MockMFARepository)(nil).UpdateLastUsedAt), ctx, id)
}
