// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/otp_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/otp_repository.go -destination=tests/mocks/otp_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOTPRepository is a mock of OTPRepository interface.
type MockOTPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOTPRepositoryMockRecorder
	isgomock struct{}
}

// MockOTPRepositoryMockRecorder is the mock recorder for MockOTPRepository.
type MockOTPRepositoryMockRecorder struct {
	mock *MockOTPRepository
}

// NewMockOTPRepository creates a new mock instance.
func NewMockOTPRepository(ctrl *gomock.Controller) *MockOTPRepository {
	mock := &MockOTPRepository{ctrl: ctrl}
	mock.recorder = &MockOTPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPRepository) EXPECT() *MockOTPRepositoryMockRecorder {
	return m.recorder
}

// CreateOTP mocks base method.
func (m *MockOTPRepository) CreateOTP(ctx context.Context, otp *models.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOTP", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOTP indicates an expected call of CreateOTP.
func (mr *MockOTPRepositoryMockRecorder) CreateOTP(ctx, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOTP", reflect.TypeOf((*MockOTPRepository)(nil).CreateOTP), ctx, otp)
}

// DeleteExpiredOTPs mocks base method.
func (m *MockOTPRepository) DeleteExpiredOTPs(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredOTPs", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredOTPs indicates an expected call of DeleteExpiredOTPs.
func (mr *MockOTPRepositoryMockRecorder) DeleteExpiredOTPs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredOTPs", reflect.TypeOf((*MockOTPRepository)(nil).DeleteExpiredOTPs), ctx)
}

// GetLatestOTPByEmail mocks base method.
func (m *MockOTPRepository) GetLatestOTPByEmail(ctx context.Context, email string) (*models.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestOTPByEmail", ctx, email)
	ret0, _ := ret[0].(*models.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestOTPByEmail indicates an expected call of GetLatestOTPByEmail.
func (mr *MockOTPRepositoryMockRecorder) GetLatestOTPByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestOTPByEmail", reflect.TypeOf((*MockOTPRepository)(nil).GetLatestOTPByEmail), ctx, email)
}

// GetOTP mocks base method.
func (m *MockOTPRepository) GetOTP(ctx context.Context, code string) (*models.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOTP", ctx, code)
	ret0, _ := ret[0].(*models.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOTP indicates an expected call of GetOTP.
func (mr *MockOTPRepositoryMockRecorder) GetOTP(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOTP", reflect.TypeOf((*MockOTPRepository)(nil).GetOTP), ctx, code)
}

// IncrementAttempts mocks base method.
func (m *MockOTPRepository) IncrementAttempts(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockOTPRepositoryMockRecorder) IncrementAttempts(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockOTPRepository)(nil).IncrementAttempts), ctx, code)
}

// MarkAsUsed mocks base method.
func (m *MockOTPRepository) MarkAsUsed(ctx context.Context, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockOTPRepositoryMockRecorder) MarkAsUsed(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockOTPRepository)(nil).MarkAsUsed), ctx, code)
}
