// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/passkey_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/passkey_repository.go -destination=tests/mocks/passkey_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPasskeyRepository is a mock of PasskeyRepository interface.
type MockPasskeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasskeyRepositoryMockRecorder
	isgomock struct{}
}

// MockPasskeyRepositoryMockRecorder is the mock recorder for MockPasskeyRepository.
type MockPasskeyRepositoryMockRecorder struct {
	mock *MockPasskeyRepository
}

// NewMockPasskeyRepository creates a new mock instance.
func NewMockPasskeyRepository(ctrl *gomock.Controller) *MockPasskeyRepository {
	mock := &MockPasskeyRepository{ctrl: ctrl}
	mock.recorder = &MockPasskeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasskeyRepository) EXPECT() *MockPasskeyRepositoryMockRecorder {
	return m.recorder
}

// GetPasskeyByCredentialID mocks base method.
func (m *MockPasskeyRepository) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (*models.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasskeyByCredentialID", ctx, credentialID)
	ret0, _ := ret[0].(*models.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasskeyByCredentialID indicates an expected call of GetPasskeyByCredentialID.
func (mr *MockPasskeyRepositoryMockRecorder) GetPasskeyByCredentialID(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasskeyByCredentialID", reflect.TypeOf((*MockPasskeyRepository)(nil).GetPasskeyByCredentialID), ctx, credentialID)
}

// GetPasskeysByUserID mocks base method.
func (m *MockPasskeyRepository) GetPasskeysByUserID(ctx context.Context, userID []byte) ([]models.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasskeysByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasskeysByUserID indicates an expected call of GetPasskeysByUserID.
func (mr *MockPasskeyRepositoryMockRecorder) GetPasskeysByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasskeysByUserID", reflect.TypeOf((*MockPasskeyRepository)(nil).GetPasskeysByUserID), ctx, userID)
}

// HasPasskey mocks base method.
func (m *MockPasskeyRepository) HasPasskey(ctx context.Context, userID []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPasskey", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPasskey indicates an expected call of HasPasskey.
func (mr *MockPasskeyRepositoryMockRecorder) HasPasskey(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPasskey", reflect.TypeOf((*MockPasskeyRepository)(nil).HasPasskey), ctx, userID)
}

// InsertPasskey mocks base method.
func (m *MockPasskeyRepository) InsertPasskey(ctx context.Context, p *models.Passkey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPasskey", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPasskey indicates an expected call of InsertPasskey.
func (mr *MockPasskeyRepositoryMockRecorder) InsertPasskey(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPasskey", reflect.TypeOf((*MockPasskeyRepository)(nil).InsertPasskey), ctx, p)
}

// UpdatePasskeySignCount mocks base method.
func (m *MockPasskeyRepository) UpdatePasskeySignCount(ctx context.Context, credentialID []byte, count uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasskeySignCount", ctx, credentialID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasskeySignCount indicates an expected call of UpdatePasskeySignCount.
func (mr *MockPasskeyRepositoryMockRecorder) UpdatePasskeySignCount(ctx, credentialID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasskeySignCount", reflect.TypeOf((*MockPasskeyRepository)(nil).UpdatePasskeySignCount), ctx, credentialID, count)
}
