// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/passkey_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/passkey_service.go -destination=tests/mocks/passkey_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasskeyService is a mock of PasskeyService interface.
type MockPasskeyService struct {
	ctrl     *gomock.Controller
	recorder *MockPasskeyServiceMockRecorder
	isgomock struct{}
}

// MockPasskeyServiceMockRecorder is the mock recorder for MockPasskeyService.
type MockPasskeyServiceMockRecorder struct {
	mock *MockPasskeyService
}

// NewMockPasskeyService creates a new mock instance.
func NewMockPasskeyService(
	ctrl *gomock.Controller,
) *MockPasskeyService {
	mock := &MockPasskeyService{ctrl: ctrl}
	mock.recorder = &MockPasskeyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasskeyService) EXPECT() *MockPasskeyServiceMockRecorder {
	return m.recorder
}

// BeginRegistration mocks base method.
func (m *MockPasskeyService) BeginRegistration(
	ctx context.Context, email string,
) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRegistration", ctx, email)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockPasskeyServiceMockRecorder) BeginRegistration(
	ctx, email any,
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "BeginRegistration",
		reflect.TypeOf((*MockPasskeyService)(nil).BeginRegistration),
		ctx, email,
	)
}

// FinishRegistration mocks base method.
func (m *MockPasskeyService) FinishRegistration(
	ctx context.Context, email string, r *http.Request,
) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", ctx, email, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockPasskeyServiceMockRecorder) FinishRegistration(
	ctx, email, r any,
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "FinishRegistration",
		reflect.TypeOf((*MockPasskeyService)(nil).FinishRegistration),
		ctx, email, r,
	)
}

// BeginVerification mocks base method.
func (m *MockPasskeyService) BeginVerification(
	ctx context.Context, email string,
) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginVerification", ctx, email)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginVerification indicates an expected call of BeginVerification.
func (mr *MockPasskeyServiceMockRecorder) BeginVerification(
	ctx, email any,
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "BeginVerification",
		reflect.TypeOf((*MockPasskeyService)(nil).BeginVerification),
		ctx, email,
	)
}

// FinishVerification mocks base method.
func (m *MockPasskeyService) FinishVerification(
	ctx context.Context, email string, r *http.Request,
) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishVerification", ctx, email, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishVerification indicates an expected call of FinishVerification.
func (mr *MockPasskeyServiceMockRecorder) FinishVerification(
	ctx, email, r any,
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "FinishVerification",
		reflect.TypeOf((*MockPasskeyService)(nil).FinishVerification),
		ctx, email, r,
	)
}

// HasPasskey mocks base method.
func (m *MockPasskeyService) HasPasskey(
	ctx context.Context, email string,
) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPasskey", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPasskey indicates an expected call of HasPasskey.
func (mr *MockPasskeyServiceMockRecorder) HasPasskey(
	ctx, email any,
) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(
		mr.mock, "HasPasskey",
		reflect.TypeOf((*MockPasskeyService)(nil).HasPasskey),
		ctx, email,
	)
}
