// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/registration_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/registration_repository.go -destination=tests/mocks/registration_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationRepository is a mock of RegistrationRepository interface.
type MockRegistrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationRepositoryMockRecorder
	isgomock struct{}
}

// MockRegistrationRepositoryMockRecorder is the mock recorder for MockRegistrationRepository.
type MockRegistrationRepositoryMockRecorder struct {
	mock *MockRegistrationRepository
}

// NewMockRegistrationRepository creates a new mock instance.
func NewMockRegistrationRepository(ctrl *gomock.Controller) *MockRegistrationRepository {
	mock := &MockRegistrationRepository{ctrl: ctrl}
	mock.recorder = &MockRegistrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationRepository) EXPECT() *MockRegistrationRepositoryMockRecorder {
	return m.recorder
}

// CountAccountTypes mocks base method.
func (m *MockRegistrationRepository) CountAccountTypes(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountTypes", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountTypes indicates an expected call of CountAccountTypes.
func (mr *MockRegistrationRepositoryMockRecorder) CountAccountTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountTypes", reflect.TypeOf((*MockRegistrationRepository)(nil).CountAccountTypes), ctx)
}

// CreateAccountType mocks base method.
func (m *MockRegistrationRepository) CreateAccountType(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountType", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountType indicates an expected call of CreateAccountType.
func (mr *MockRegistrationRepositoryMockRecorder) CreateAccountType(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountType", reflect.TypeOf((*MockRegistrationRepository)(nil).CreateAccountType), ctx, name)
}

// DeleteAccountType mocks base method.
func (m *MockRegistrationRepository) DeleteAccountType(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountType", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountType indicates an expected call of DeleteAccountType.
func (mr *MockRegistrationRepositoryMockRecorder) DeleteAccountType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountType", reflect.TypeOf((*MockRegistrationRepository)(nil).DeleteAccountType), ctx, id)
}

// GetAccountTypeIDByName mocks base method.
func (m *MockRegistrationRepository) GetAccountTypeIDByName(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountTypeIDByName", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountTypeIDByName indicates an expected call of GetAccountTypeIDByName.
func (mr *MockRegistrationRepositoryMockRecorder) GetAccountTypeIDByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountTypeIDByName", reflect.TypeOf((*MockRegistrationRepository)(nil).GetAccountTypeIDByName), ctx, name)
}

// GetClientsByAccountTypeID mocks base method.
func (m *MockRegistrationRepository) GetClientsByAccountTypeID(ctx context.Context, id int) ([]repository.AccountTypeClientRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsByAccountTypeID", ctx, id)
	ret0, _ := ret[0].([]repository.AccountTypeClientRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsByAccountTypeID indicates an expected call of GetClientsByAccountTypeID.
func (mr *MockRegistrationRepositoryMockRecorder) GetClientsByAccountTypeID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsByAccountTypeID", reflect.TypeOf((*MockRegistrationRepository)(nil).GetClientsByAccountTypeID), ctx, id)
}

// GetRegistrationConfig mocks base method.
func (m *MockRegistrationRepository) GetRegistrationConfig(ctx context.Context, limit, offset int) ([]repository.AccountTypeClientRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationConfig", ctx, limit, offset)
	ret0, _ := ret[0].([]repository.AccountTypeClientRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationConfig indicates an expected call of GetRegistrationConfig.
func (mr *MockRegistrationRepositoryMockRecorder) GetRegistrationConfig(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationConfig", reflect.TypeOf((*MockRegistrationRepository)(nil).GetRegistrationConfig), ctx, limit, offset)
}

// SyncPreapprovedClients mocks base method.
func (m *MockRegistrationRepository) SyncPreapprovedClients(ctx context.Context, accountTypeID int, clientIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPreapprovedClients", ctx, accountTypeID, clientIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncPreapprovedClients indicates an expected call of SyncPreapprovedClients.
func (mr *MockRegistrationRepositoryMockRecorder) SyncPreapprovedClients(ctx, accountTypeID, clientIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPreapprovedClients", reflect.TypeOf((*MockRegistrationRepository)(nil).SyncPreapprovedClients), ctx, accountTypeID, clientIDs)
}

// UpdateAccountType mocks base method.
func (m *MockRegistrationRepository) UpdateAccountType(ctx context.Context, id int, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountType", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountType indicates an expected call of UpdateAccountType.
func (mr *MockRegistrationRepositoryMockRecorder) UpdateAccountType(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountType", reflect.TypeOf((*MockRegistrationRepository)(nil).UpdateAccountType), ctx, id, name)
}
