// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/registration_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/registration_service.go -destination=tests/mocks/registration_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// ActivateAccount mocks base method.
func (m *MockRegistrationService) ActivateAccount(ctx context.Context, req dto.ActivateAccountRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateAccount", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateAccount indicates an expected call of ActivateAccount.
func (mr *MockRegistrationServiceMockRecorder) ActivateAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateAccount", reflect.TypeOf((*MockRegistrationService)(nil).ActivateAccount), ctx, req)
}

// CheckInvitation mocks base method.
func (m *MockRegistrationService) CheckInvitation(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvitation", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckInvitation indicates an expected call of CheckInvitation.
func (mr *MockRegistrationServiceMockRecorder) CheckInvitation(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvitation", reflect.TypeOf((*MockRegistrationService)(nil).CheckInvitation), ctx, code)
}

// CreateAccountType mocks base method.
func (m *MockRegistrationService) CreateAccountType(ctx context.Context, req dto.UpsertAccountTypeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountType", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccountType indicates an expected call of CreateAccountType.
func (mr *MockRegistrationServiceMockRecorder) CreateAccountType(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountType", reflect.TypeOf((*MockRegistrationService)(nil).CreateAccountType), ctx, req)
}

// DeleteAccountType mocks base method.
func (m *MockRegistrationService) DeleteAccountType(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountType", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountType indicates an expected call of DeleteAccountType.
func (mr *MockRegistrationServiceMockRecorder) DeleteAccountType(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountType", reflect.TypeOf((*MockRegistrationService)(nil).DeleteAccountType), ctx, id)
}

// GetClientsByAccountTypeID mocks base method.
func (m *MockRegistrationService) GetClientsByAccountTypeID(ctx context.Context, id int) (*dto.AccountTypeConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsByAccountTypeID", ctx, id)
	ret0, _ := ret[0].(*dto.AccountTypeConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsByAccountTypeID indicates an expected call of GetClientsByAccountTypeID.
func (mr *MockRegistrationServiceMockRecorder) GetClientsByAccountTypeID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsByAccountTypeID", reflect.TypeOf((*MockRegistrationService)(nil).GetClientsByAccountTypeID), ctx, id)
}

// GetRegistrationConfig mocks base method.
func (m *MockRegistrationService) GetRegistrationConfig(ctx context.Context) (*dto.RegistrationConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationConfig", ctx)
	ret0, _ := ret[0].(*dto.RegistrationConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationConfig indicates an expected call of GetRegistrationConfig.
func (mr *MockRegistrationServiceMockRecorder) GetRegistrationConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationConfig", reflect.TypeOf((*MockRegistrationService)(nil).GetRegistrationConfig), ctx)
}

// UpdateAccountType mocks base method.
func (m *MockRegistrationService) UpdateAccountType(ctx context.Context, req dto.UpsertAccountTypeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountType", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountType indicates an expected call of UpdateAccountType.
func (mr *MockRegistrationServiceMockRecorder) UpdateAccountType(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountType", reflect.TypeOf((*MockRegistrationService)(nil).UpdateAccountType), ctx, req)
}
