// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/role_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/role_service.go -destination=tests/mocks/role_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleService is a mock of RoleService interface.
type MockRoleService struct {
	ctrl     *gomock.Controller
	recorder *MockRoleServiceMockRecorder
	isgomock struct{}
}

// MockRoleServiceMockRecorder is the mock recorder for MockRoleService.
type MockRoleServiceMockRecorder struct {
	mock *MockRoleService
}

// NewMockRoleService creates a new mock instance.
func NewMockRoleService(ctrl *gomock.Controller) *MockRoleService {
	mock := &MockRoleService{ctrl: ctrl}
	mock.recorder = &MockRoleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleService) EXPECT() *MockRoleServiceMockRecorder {
	return m.recorder
}

// CreateRole mocks base method.
func (m *MockRoleService) CreateRole(ctx context.Context, req dto.RoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRoleServiceMockRecorder) CreateRole(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRoleService)(nil).CreateRole), ctx, req)
}

// DeleteRole mocks base method.
func (m *MockRoleService) DeleteRole(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockRoleServiceMockRecorder) DeleteRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockRoleService)(nil).DeleteRole), ctx, id)
}

// GetAllExceptIDP mocks base method.
func (m *MockRoleService) GetAllExceptIDP(ctx context.Context, limit, page int, keyword string) (*dto.RoleListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllExceptIDP", ctx, limit, page, keyword)
	ret0, _ := ret[0].(*dto.RoleListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExceptIDP indicates an expected call of GetAllExceptIDP.
func (mr *MockRoleServiceMockRecorder) GetAllExceptIDP(ctx, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExceptIDP", reflect.TypeOf((*MockRoleService)(nil).GetAllExceptIDP), ctx, limit, page, keyword)
}

// GetAuthorizedRoles mocks base method.
func (m *MockRoleService) GetAuthorizedRoles(ctx context.Context, userID uuid.UUID, limit, page int, keyword string) (*dto.RoleListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizedRoles", ctx, userID, limit, page, keyword)
	ret0, _ := ret[0].(*dto.RoleListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizedRoles indicates an expected call of GetAuthorizedRoles.
func (mr *MockRoleServiceMockRecorder) GetAuthorizedRoles(ctx, userID, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizedRoles", reflect.TypeOf((*MockRoleService)(nil).GetAuthorizedRoles), ctx, userID, limit, page, keyword)
}

// GetFilteredRoleList mocks base method.
func (m *MockRoleService) GetFilteredRoleList(ctx context.Context, permissions []string, userID uuid.UUID, limit, page int, keyword string) (*dto.RoleListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredRoleList", ctx, permissions, userID, limit, page, keyword)
	ret0, _ := ret[0].(*dto.RoleListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredRoleList indicates an expected call of GetFilteredRoleList.
func (mr *MockRoleServiceMockRecorder) GetFilteredRoleList(ctx, permissions, userID, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredRoleList", reflect.TypeOf((*MockRoleService)(nil).GetFilteredRoleList), ctx, permissions, userID, limit, page, keyword)
}

// GetRoleByID mocks base method.
func (m *MockRoleService) GetRoleByID(ctx context.Context, id int) (*dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, id)
	ret0, _ := ret[0].(*dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRoleServiceMockRecorder) GetRoleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRoleService)(nil).GetRoleByID), ctx, id)
}

// GetRoleList mocks base method.
func (m *MockRoleService) GetRoleList(ctx context.Context, limit, page int, keyword string) (*dto.RoleListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleList", ctx, limit, page, keyword)
	ret0, _ := ret[0].(*dto.RoleListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleList indicates an expected call of GetRoleList.
func (mr *MockRoleServiceMockRecorder) GetRoleList(ctx, limit, page, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleList", reflect.TypeOf((*MockRoleService)(nil).GetRoleList), ctx, limit, page, keyword)
}

// SearchRoles mocks base method.
func (m *MockRoleService) SearchRoles(ctx context.Context, keyword string) (*dto.RoleListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRoles", ctx, keyword)
	ret0, _ := ret[0].(*dto.RoleListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRoles indicates an expected call of SearchRoles.
func (mr *MockRoleServiceMockRecorder) SearchRoles(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRoles", reflect.TypeOf((*MockRoleService)(nil).SearchRoles), ctx, keyword)
}

// UpdateRole mocks base method.
func (m *MockRoleService) UpdateRole(ctx context.Context, id int, req dto.RoleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockRoleServiceMockRecorder) UpdateRole(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockRoleService)(nil).UpdateRole), ctx, id, req)
}
