// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/role_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/role_repository.go -destination=tests/mocks/role_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// CountDistinctBoundRoles mocks base method.
func (m *MockRoleRepository) CountDistinctBoundRoles(ctx context.Context, userID []byte, keyword string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctBoundRoles", ctx, userID, keyword)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctBoundRoles indicates an expected call of CountDistinctBoundRoles.
func (mr *MockRoleRepositoryMockRecorder) CountDistinctBoundRoles(ctx, userID, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctBoundRoles", reflect.TypeOf((*MockRoleRepository)(nil).CountDistinctBoundRoles), ctx, userID, keyword)
}

// CountRoles mocks base method.
func (m *MockRoleRepository) CountRoles(ctx context.Context, keyword string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRoles", ctx, keyword)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRoles indicates an expected call of CountRoles.
func (mr *MockRoleRepositoryMockRecorder) CountRoles(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRoles", reflect.TypeOf((*MockRoleRepository)(nil).CountRoles), ctx, keyword)
}

// CreateRole mocks base method.
func (m *MockRoleRepository) CreateRole(ctx context.Context, role models.Role) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, role)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRoleRepositoryMockRecorder) CreateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRoleRepository)(nil).CreateRole), ctx, role)
}

// Delete mocks base method.
func (m *MockRoleRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepository)(nil).Delete), ctx, id)
}

// FetchPermissionsForRoles mocks base method.
func (m *MockRoleRepository) FetchPermissionsForRoles(ctx context.Context, roleIDs []int) (map[int][]models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPermissionsForRoles", ctx, roleIDs)
	ret0, _ := ret[0].(map[int][]models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPermissionsForRoles indicates an expected call of FetchPermissionsForRoles.
func (mr *MockRoleRepositoryMockRecorder) FetchPermissionsForRoles(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPermissionsForRoles", reflect.TypeOf((*MockRoleRepository)(nil).FetchPermissionsForRoles), ctx, roleIDs)
}

// GetByID mocks base method.
func (m *MockRoleRepository) GetByID(ctx context.Context, id int) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleRepository)(nil).GetByID), ctx, id)
}

// ListAllExceptIdP mocks base method.
func (m *MockRoleRepository) ListAllExceptIdP(ctx context.Context, limit, offset int, keyword string) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllExceptIdP", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllExceptIdP indicates an expected call of ListAllExceptIdP.
func (mr *MockRoleRepositoryMockRecorder) ListAllExceptIdP(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllExceptIdP", reflect.TypeOf((*MockRoleRepository)(nil).ListAllExceptIdP), ctx, limit, offset, keyword)
}

// ListDistinctBoundRoles mocks base method.
func (m *MockRoleRepository) ListDistinctBoundRoles(ctx context.Context, limit, offset int, userID []byte, keyword string) ([]models.RoleWithMetaData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDistinctBoundRoles", ctx, limit, offset, userID, keyword)
	ret0, _ := ret[0].([]models.RoleWithMetaData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistinctBoundRoles indicates an expected call of ListDistinctBoundRoles.
func (mr *MockRoleRepositoryMockRecorder) ListDistinctBoundRoles(ctx, limit, offset, userID, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistinctBoundRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListDistinctBoundRoles), ctx, limit, offset, userID, keyword)
}

// ListRoles mocks base method.
func (m *MockRoleRepository) ListRoles(ctx context.Context, limit, offset int, keyword string) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, limit, offset, keyword)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRoleRepositoryMockRecorder) ListRoles(ctx, limit, offset, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListRoles), ctx, limit, offset, keyword)
}

// SearchRoles mocks base method.
func (m *MockRoleRepository) SearchRoles(ctx context.Context, keyword string) ([]models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRoles", ctx, keyword)
	ret0, _ := ret[0].([]models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRoles indicates an expected call of SearchRoles.
func (mr *MockRoleRepositoryMockRecorder) SearchRoles(ctx, keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRoles", reflect.TypeOf((*MockRoleRepository)(nil).SearchRoles), ctx, keyword)
}

// UpdateRole mocks base method.
func (m *MockRoleRepository) UpdateRole(ctx context.Context, role models.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockRoleRepositoryMockRecorder) UpdateRole(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockRoleRepository)(nil).UpdateRole), ctx, role)
}
