// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/token_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/token_service.go -destination=tests/mocks/token_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
