// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/service/user_service.go
//
// Generated by this command:
//
//	mockgen -source=backend/internal/service/user_service.go -destination=backend/tests/mocks/user_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Iskolutions-Capstone-Dev-Team/Identity-Provider/internal/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserService) ChangePassword(ctx context.Context, id uuid.UUID, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, id, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserServiceMockRecorder) ChangePassword(ctx, id, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserService)(nil).ChangePassword), ctx, id, oldPassword, newPassword)
}

// CreateAdminUser mocks base method.
func (m *MockUserService) CreateAdminUser(ctx context.Context, req dto.PostAdminUserRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUser", ctx, req)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUser indicates an expected call of CreateAdminUser.
func (mr *MockUserServiceMockRecorder) CreateAdminUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUser", reflect.TypeOf((*MockUserService)(nil).CreateAdminUser), ctx, req)
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(ctx context.Context, req dto.UserRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), ctx, req)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, id)
}

// GetAdminUserList mocks base method.
func (m *MockUserService) GetAdminUserList(ctx context.Context, limit, page int) (*dto.UserResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserList", ctx, limit, page)
	ret0, _ := ret[0].(*dto.UserResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserList indicates an expected call of GetAdminUserList.
func (mr *MockUserServiceMockRecorder) GetAdminUserList(ctx, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserList", reflect.TypeOf((*MockUserService)(nil).GetAdminUserList), ctx, limit, page)
}

// GetBoundUserList mocks base method.
func (m *MockUserService) GetBoundUserList(ctx context.Context, limit, page int, userID uuid.UUID) (*dto.UserSimplifiedResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoundUserList", ctx, limit, page, userID)
	ret0, _ := ret[0].(*dto.UserSimplifiedResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoundUserList indicates an expected call of GetBoundUserList.
func (mr *MockUserServiceMockRecorder) GetBoundUserList(ctx, limit, page, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoundUserList", reflect.TypeOf((*MockUserService)(nil).GetBoundUserList), ctx, limit, page, userID)
}

// GetFilteredUserList mocks base method.
func (m *MockUserService) GetFilteredUserList(ctx context.Context, permissions []string, userID uuid.UUID, limit, page int) (*dto.UserSimplifiedResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredUserList", ctx, permissions, userID, limit, page)
	ret0, _ := ret[0].(*dto.UserSimplifiedResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredUserList indicates an expected call of GetFilteredUserList.
func (mr *MockUserServiceMockRecorder) GetFilteredUserList(ctx, permissions, userID, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredUserList", reflect.TypeOf((*MockUserService)(nil).GetFilteredUserList), ctx, permissions, userID, limit, page)
}

// GetMe mocks base method.
func (m *MockUserService) GetMe(ctx context.Context, userID uuid.UUID) (*dto.UserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMe", ctx, userID)
	ret0, _ := ret[0].(*dto.UserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMe indicates an expected call of GetMe.
func (mr *MockUserServiceMockRecorder) GetMe(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMe", reflect.TypeOf((*MockUserService)(nil).GetMe), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockUserService) GetUserByEmail(ctx context.Context, email string) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserServiceMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserService)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserService) GetUserByID(ctx context.Context, id uuid.UUID) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserService)(nil).GetUserByID), ctx, id)
}

// GetUserList mocks base method.
func (m *MockUserService) GetUserList(ctx context.Context, limit, page int) (*dto.UserSimplifiedResponseList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserList", ctx, limit, page)
	ret0, _ := ret[0].(*dto.UserSimplifiedResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserList indicates an expected call of GetUserList.
func (mr *MockUserServiceMockRecorder) GetUserList(ctx, limit, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserList", reflect.TypeOf((*MockUserService)(nil).GetUserList), ctx, limit, page)
}

// SyncAdminClientAccess mocks base method.
func (m *MockUserService) SyncAdminClientAccess(ctx context.Context, id uuid.UUID, clientIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAdminClientAccess", ctx, id, clientIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncAdminClientAccess indicates an expected call of SyncAdminClientAccess.
func (mr *MockUserServiceMockRecorder) SyncAdminClientAccess(ctx, id, clientIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAdminClientAccess", reflect.TypeOf((*MockUserService)(nil).SyncAdminClientAccess), ctx, id, clientIDs)
}

// UpdateUserName mocks base method.
func (m *MockUserService) UpdateUserName(ctx context.Context, id uuid.UUID, req dto.UpdateUserNameRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserName", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserName indicates an expected call of UpdateUserName.
func (mr *MockUserServiceMockRecorder) UpdateUserName(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserName", reflect.TypeOf((*MockUserService)(nil).UpdateUserName), ctx, id, req)
}

// UpdateUserPassword mocks base method.
func (m *MockUserService) UpdateUserPassword(ctx context.Context, id uuid.UUID, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, id, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockUserServiceMockRecorder) UpdateUserPassword(ctx, id, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockUserService)(nil).UpdateUserPassword), ctx, id, newPassword)
}

// UpdateUserPasswordByEmail mocks base method.
func (m *MockUserService) UpdateUserPasswordByEmail(ctx context.Context, email, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordByEmail", ctx, email, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordByEmail indicates an expected call of UpdateUserPasswordByEmail.
func (mr *MockUserServiceMockRecorder) UpdateUserPasswordByEmail(ctx, email, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordByEmail", reflect.TypeOf((*MockUserService)(nil).UpdateUserPasswordByEmail), ctx, email, newPassword)
}

// UpdateUserRole mocks base method.
func (m *MockUserService) UpdateUserRole(ctx context.Context, id uuid.UUID, roleID *int, adminID uuid.UUID, permissions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", ctx, id, roleID, adminID, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockUserServiceMockRecorder) UpdateUserRole(ctx, id, roleID, adminID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockUserService)(nil).UpdateUserRole), ctx, id, roleID, adminID, permissions)
}

// UpdateUserStatus mocks base method.
func (m *MockUserService) UpdateUserStatus(ctx context.Context, id uuid.UUID, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, id, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockUserServiceMockRecorder) UpdateUserStatus(ctx, id, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockUserService)(nil).UpdateUserStatus), ctx, id, newStatus)
}
