export const ROUTE_PATHS = Object.freeze({
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  REGISTER_SET_PASSWORD: "/register/set-password",
  CALLBACK: "/callback",
  LOGOUT: "/logout",
  ERROR: "/error",
  ONE_PORTAL: "/one-portal",
  DASHBOARD: "/dashboard",
  USER_POOL: "/user-pool",
  USER_POOL_CREATE: "/user-pool/create",
  ROLES: "/roles",
  ROLES_CREATE: "/roles/create",
  AUDIT_LOGS: "/audit-logs",
  FAQ: "/faq",
  APP_CLIENT: "/app-client",
  APP_CLIENT_CREATE: "/app-client/create",
  REGISTRATION: "/registration",
  REGISTRATION_CREATE: "/registration/create",
  PROFILE: "/profile",
});
